version: "3"

services:
  db:
    image: mysql
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "hyundai"
      MYSQL_DATABASE: "hyundai_faq_db"
      MYSQL_USER: "Hyundai"
      MYSQL_PASSWORD: "hyundai"
    ports:
      - "3306:3306"